version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: feedback-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: feedback-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
